---
title: "Reading Habits Freewrite"
# just a low-pressure place to write!
# bibliography: refs.bib
# csl: apa.csl
# output: html_document
output: 
  bookdown::html_document2:
  # bookdown::word_document2:
  #   reference_docx: "template_calibri.docx"
    number_sections: false
always_allow_html: true
bibliography: refs.bib
csl: apa.csl
# biblio-title: References
---

## Parent Influence on Reading and Academics

### Reading Motivation and Habits

**TK Add info about reading achievement outcomes!**

**[TK NOTE - original version of first paragraph in this section]** It is well-established that parents influence their children's reading attitudes and behaviors in early childhood through home literacy practices such as shared book reading [@Baker.1997; @Hume.2015]. Although more limited, additional research suggests that parents continue to influence reading attitudes and behaviors during later childhood and adolescence [@Lim.2015; @Pelletier.2024; see @Klauda.2009 for a review of earlier work]. These studies have focused on the effects of parents' reading-specific behaviors, such as encouraging adolescents to read in their free time, discussing books, and going to the bookstore or library together [@Lim.2015; @Pelletier.2024].

**[TK NOTE - alternative version of first paragraph in this section is in manuscript document]**

What parent practices or behaviors support strong reading motivation and habits?

**TK** I need to say more about Klauda 2009 but WHAT?

-   Parent reading attitudes [@Lim.2015]
-   Parent behaviors that support reading (e.g., providing books, discussing reading, visiting the library together) [@Lim.2015]

@Lim.2015

-   Parent reading attitudes and parent support predicted adolescent reading habits, mediated by adolescent reading attitudes

In a detailed review of how parental involvement supports adolescents' academic achievement, @Klauda.2009 discusses two theoretical models

### Academic Achievement in Middle School

Like with reading motivation and habits, parents play an important role in students' academic performance. Parental involvement in students' education is positively associated with academic achievement in reading and other subjects throughout primary [@Galindo.2012; CITE **TK**] and secondary schooling (CITE **TK**). Over the past few decades, multiple meta-analyses have confirmed the value of parental involvement among students from various racial, ethnic, and socioeconomic backgrounds [CITE **TK**]. Parental involvement can take a variety of forms, including both home-based (e.g., **TK** examples) and school-based activities (e.g., **TK** examples). Parents can also be more indirectly involved in their adolescents' education by practicing academic socialization strategies such as discussing the value of education or encouraging students' education and career goals. Findings from a meta-analysis by @Hill.2009 suggest that during middle school, academic socialization strategies may be a particularly effective way for parents to provide educational support.

### Academic Socialization

**TK** add text here - I'm not sure yet where this subsection should go....

@Hill.2009 define academic socialization as parental involvement that includes "communicating parental expectations for education and its value or utility, linking school-work to current events, fostering educational and occupational aspirations, discussing learning strategies with children, and making preparations and plans for the future" (p. 742). This definition builds off of [**TK** other stuff about socialization].

**TK should I move this paragraph? shorten this (seems very long)?** In a meta-analysis that examined the relationship between parent involvement and academic achievement in middle school, @Hill.2009 found that academic socialization was more strongly associated with academic achievement than either home- or school-based involvement. The authors suggested that both the structure of middle schools and developmental changes during early adolescence may make academic socialization more effective than more direct home- and school-based practices. Compared with elementary schools, the organizational structure of middle schools is much more complex, with multiple teachers per student and each teacher serving many more students. This complexity limits opportunities for parents to develop partnerships with teachers and learn about the curriculum. Because academic socialization practices emphasize the value of education more broadly, this form of parental involvement may be less dependent on parents' interactions with teachers and knowledge of specific curricula. Academic socialization can also serve as a developmentally appropriate form of parent involvement. During the middle school years, adolescents typically seek greater autonomy as they begin to set goals and make decisions more independently (CITE **TK**). Academic socialization strategies, such as discussing or modeling the value of education, allow adolescents to exercise independence in daily school-related activities and decisions. Adolescents may not be as receptive to direct parent involvement at home or at school, which could interfere with their sense of autonomy.
