---
title: "Reading Habits Manuscript Draft"
# bibliography: refs.bib
# csl: apa.csl
# output: html_document
output: 
  bookdown::html_document2:
  bookdown::word_document2:
    reference_docx: "template_calibri.docx"
    number_sections: false
always_allow_html: true
bibliography: refs.bib
csl: apa.csl
# biblio-title: References
---

# Abstract

There is ample evidence that parent literacy behaviors (e.g., daily book reading) influence the reading attitudes and habits of young children. However, few studies have examined how parents may continue to promote strong reading habits during adolescence. Although adolescence is a time of increased independence, family remains highly influential in the beliefs and behaviors of Latinx adolescents, and it is likely that parents of Latinx youth continue to influence reading attitudes and habits during this time. **Because reading is widely considered critical for academic success, broader messaging from parents about academics (i.e., educational modeling) may influence teens' reading attitudes, and in turn, their reading habits. (TK - NOTE - don't forget this important link/message in writing the intro!).** Guided by work grounded in academic socialization and ecological systems perspectives (**TK** - or just SEVT??? what about Garcia-Coll's integrative model?) **TK UPDATE THEORIES**, the present study longitudinally examined whether Latinx teens' perceptions of parents' educational modeling (Time 1) promoted teens' later reading habits (Time 3) via reading attitudes (Time 2) (*N* = 329). Teens' perceptions of their parents' educational modeling predicted teens' reading attitudes, and teens' reading attitudes predicted their reading habits. Teens' reading attitudes mediated the relationship between their perceptions of parents' educational modeling and teens' reading habits. Based on the results of confirmatory factor analyses, we examined separate models for educational modeling of mothers and fathers. These results indicate that parents continue to play an important role in supporting reading into adolescence. By modeling broader educational values, parents of Latinx youth can promote positive views of reading to support strong reading habits.

# Introduction

Although reading is considered critical for academic success, both interest in reading and frequency of reading decreases during adolescence [@Scholastic.2022]. In response, researchers have sought to understand what promotes positive reading attitudes and behaviors among adolescents [@Broeder.2013; @Lim.2015; @Pelletier.2024]. This research has shown that, like in early childhood [@Baker.1997], parents play an important role in supporting adolescents' reading attitudes and habits [@Klauda.2009; @Lim.2015; @Pelletier.2024]. Unfortunately, few studies have focused on Latinx adolescents' reading attitudes [@Griffin.2020; @Quirk.2020; @Sutter.2022] or habits [@Sutter.2022]. This work is necessary to support Latinx youth, many of whom are at risk of lower achievement outcomes in reading [@Carris.2024; @Reardon.2009]. Although outside of the reading domain, prior research shows that parent beliefs and behaviors influence school-related outcomes (e.g., academic self-efficacy, math/science achievement) among Latinx adolescents [@Cross.2019i9o; @Delgado.2021]. These outcomes are consistent with an academic socialization framework [@Chun.2019; @Hill.2010] that aligns with an ecological systems approach [@Bronfenbrenner.1986]. Through a longitudinal design, the present study examines how parents' general educational beliefs and behaviors (i.e., education modeling), may predict reading attitudes and habits among Latinx adolescents.

## The Importance of Adolescent Reading Attitudes and Habits

In the early years of schooling, there is great emphasis on developing proficiency in foundational reading skills, such as decoding and memorizing sight words. As students progress into late childhood and adolescence, reading demands increase, with considerable academic content being delivered in the form of textbooks, novels, informational articles, and other written materials [@Wendt.2013]. With this shift, there are clear advantages to being an avid reader during adolescence: frequent reading supports vocabulary development [@Stanovich.2009], reading comprehension [@McGeown.2015; @Torppa.2020], and achievement [@Allington.2014]. Similarly, more positive reading attitudes are associated with better reading comprehension [@Conlon.2006] and higher levels of reading achievement [**CITE TK**].

However, despite these benefits, both time spent on book reading [@Duncan.2016; @Scholastic.2022] and enjoyment of book reading [@Scholastic.2022] decrease during adolescence. A recent *Kids & Family Reading Report* [@Scholastic.2022] revealed that only 46% of adolescents 'love/like a lot' reading books for fun, compared to 70% of children ages 6 to 8. Similarly, only 59% of adolescents reported that they read books for fun on 1 or more days per week, compared to 89% of children ages 6 to 8. The reading habits of today's youth are of particular concern, as researchers have witnessed a steady decline in the use of print media across several generations. For example, only 16% of 12th graders reported daily reading of books or magazines in 2016, compared to 60% in the late 1970s [@Twenge.2019].

### Defining Reading Motivation and Attitudes

**TK Add something about reading attitudes as part of the construct of reading motivation?**

### Latinx Adolescents

In the United States, gaps in reading achievement between White and Latinx youth have been well-documented [@Carris.2024; @Reardon.2009], with Latinx youth earning lower scores than their White peers. Eliminating this gap likely requires a multi-pronged approach, as researchers have indicated a number of contributing factors, including local immigration policies and practices [@Carris.2024], English language proficiency [@Reardon.2009], and family socioeconomic status [@Reardon.2009]. In addition to these, the reading achievement of Latinx youth are likely influenced by their reading attitudes and habits (**CITE TK**), as found with other populations of adolescents [@McGeown.2015; @Toste.2020].

There is little research specifically addressing the reading habits of Latinx children and adolescents (**TK** is there ANY research on this?).

Students' reading attitudes and habits are both...\
\
**TK some things to consider citing:**\
Griffin, R. A., & Farran, L. K. (2021). Reconsidering the reading motivation of adolescent Latinx multilingual learners. *The Reading Professor*, *44*(1). <https://scholar.stjohns.edu/thereadingprofessor/vol44/iss1/5>

Griffin, R. A., Farran, L. K., & Mindrila, D. (2020). Reading motivation in bi/multilingual Latinx adolescents: An exploratory structural equation model. *Reading Psychology*, *41*(8), 856–892. <https://doi.org/10.1080/02702711.2020.1801540>

Neugebauer, S. R., & Blair, E. E. (2020). “I know how to read and all, but...”: Disciplinary reading constructions of middle school students of color. *Journal of Literacy Research*, *52*(3), 316–340. <https://doi.org/10.1177/1086296x20938780>

Quirk, M., Swami, S., Loera, G., & Garcia, S. (2020). Latinx adolescents’ reading motivation profiles and associations with higher education aspirations. *Literacy Research and Instruction*, *59*(3), 218–239. <https://doi.org/10.1080/19388071.2020.1752862>

Sutter, C. C., & Campbell, L. O. (2022). The role of academic self-determined reading motivation, reading self-concept, home reading environment, and student reading behavior in reading achievement among American Indian and Hispanic students. *Contemporary Educational Psychology*, *70*, 102093. <https://doi.org/10.1016/j.cedpsych.2022.102093>

## Parental Influence on Reading and Academics

**TK overview about reading/academic achievement/academic socialization and parent influence**

Parents play an important role in students' learning experiences, influencing not only achievement and performance outcomes [**TK** cite] but also more affective aspects of learning, such as students' attitudes and motivation [**TK** cite]. This influential role is expected within theoretical frameworks that reflect an ecological systems perspective (**TK** perspective? approach? something else?) [**TK** cite Bronfenbrenner?], in which multiple systems (e.g., home, school) interact and contribute to an individual's development.

### Reading Motivation (Attitudes?) and Habits

**TK update motivation –\> attitudes or decide how to address this**

It is well-established that parent practices shape children's reading motivation and habits [@Baker.1997; @Hume.2015; @Klauda.2009; @Lim.2015; @Pelletier.2024]. Parents influence early reading motivation and habits by both shaping the home environment (e.g., providing books) engaging in reading-related activities (e.g., shared reading, going to the library) [@Baker.1997; @Hume.2015]. Although much research in this area focuses on home literacy practices for young children [@Hume.2015], parents continue to influence reading motivation and habits into adolescence [@Klauda.2009; @Lim.2015; @Pelletier.2024].

### Parent Influence in Latinx Families

TK WRITE THINGS HERE

## The Present Study

It is well-established that parents influence young children's reading motivation and habits [@Baker.1997]. In turn, motivated readers perform better on measures of reading ability [@Baker.1999]. Although many studies focus on younger children, additional research indicates that parents can continue to promote positive reading attitudes and behaviors during adolescence [@Klauda.2009]. [**TK I don't like this next sentence.**] However, these studies have focused on the impact of parent behaviors that are explicitly reading- or book-specific **(e.g., TK, TK),** therefore providing little insight into alternative ways in which parents may promote positive reading attitudes and habits in adolescence. Furthermore, although Latinx youth are at risk of lower reading achievement levels than their White peers [@Carris.2024; @Reardon.2009], few studies have explored reading motivation and habits within this population [**TK** cite any studies that have].

In the present study, we examined how Latinx teens' perceptions of parents' educational modeling (i.e., educational modeling) may influence their later reading habits. We predicted that educational modeling would positively predict teens' later reading habits and that this relationship would be mediated by teens' reading attitudes. These predictions were grounded in SEVT [@Eccles.2020] and theories (**TK theories?? or just existing empirical work**) of academic socialization (**TK cite cite cite**). **TK** ecological models? **TK** Garcia Coll's integrative model?

Within SEVT, adolescents' perceptions of socializers' (e.g., parents') beliefs and behaviors indirectly influence subjective task values, which in turn influence achievement-related choices. In the context of the current study, we identify teens' perceptions of educational modeling as their perceptions of socializers' beliers and behaviors. Similarly, we consider reading attitudes to be the subjective task values and reading habits to be achievement-related choices.

Although Eccles and Wigfield (2020) recognize that students' sociocultural contexts (e.g., race, ethnicity) play a meaningful role in academic motivation, SEVT in its current state provides little explanation for how these processes operate. Therefore, we have also drawn from work on academic socialization (**TK cite**), including academic socialization of Latinx youth, as motivation for our predictions. **TK ADD MORE HERE**

# Method

## Participants

**[TK Remove this note - Comment: I am basing the participant information for the larger study off of the description in Delgado et al., 2021.]**

This study utilizes a subset of data that were collected as part of a larger, 3-year longitudinal project on academic identity and achievement among Latinx adolescents in the southwestern United States [**TK** add citations for other Alcance studies]. Inclusion criteria for the larger study were as follows: (a) adolescents were in 8th grade, (b) adolescents resided with biological mothers and/or biological or long-term adoptive fathers, and (c) biological mothers and/or biological fathers reported origins from Latin America and/or the Latin Caribbean. Adolescents and their families were recruited from five school districts in the southwestern United States between 2015 and 2017. Bilingual project staff attempted to contact 1598 families who had given schools consent to open records and share their contact information. Of these 1598 families, 531 families met eligibility criteria, and 329 families completed study activities in the first year.

## Procedure

**TK add procedures here**

## Measures

**TK add info about reading attitude measure**

The (**TK** add name) was used to measure reading motivation, or more specifically, reading attitudes.[^1]

[^1]: The (**TK** name) was designed to measure students' reading attitudes, or (TK definition of reading attitudes). @Baker.1997 consider reading attitudes to be part of a broader construct of reading motivation, which may also include (**TK** other types of reading motivation). For the purposes of this paper, we primarily use the term reading motivation... (**TK** add explanation)

## Data Analysis

# References
