---
title: "Text Removed from Reading Habits Manuscript Draft"
# bibliography: refs.bib
# csl: apa.csl
# output: html_document
output: 
  bookdown::html_document2:
  bookdown::word_document2:
    reference_docx: "template_calibri.docx"
    number_sections: false
always_allow_html: true
bibliography: refs.bib
csl: apa.csl
# biblio-title: References
---

Removed from intro: 

TK Do I want this paragraph (below)? Due to the shift from "learning to read" to "reading to learn" that occurs in middle-to-late elementary school (cite TK), both adolescents and their parents are likely more focused on gaining content knowledge than reading for its own sake. Because reading is so closely tied to adolescents' academic learning (cite TK), however, parents' broader educational behaviors or beliefs (i.e., educational modeling) have the potential to influence adolescents' reading attitudes and habits. Although this process may occur among families of many different ethnic-racial backgrounds, there is reason to believe the effect of parents' educational modeling may be particularly salient for Latinx adolescents. TK stuff about familism etc maybe


Although previous research has examined the role of Latinx parents in children's early literacy practices (TK CITE), we lack empirical evidence on how Latinx parents can continue to promote positive reading attitudes and habits during adolescence. Research with other populations of adolescents suggests that parent involvement remains important for adolescents' reading attitudes and behaviors [@Pelletier.2024]. 


It is well-established that linguistic and cognitive skills (e.g., vocabulary, working memory) support reading achievement among children and adolescents [@Kudo.2015; @Peng.2018; @Peng.2019].

As we have described, reading achievement is a critical topic of investigation for both researchers and policy makers. In addition to the role of individuals' linguistic and cognitive skills (e.g., vocabulary, working memory) [@Kudo.2015; @Peng.2018], researchers have

Because students' reading attitudes and habits are associated with reading achievement and skills (e.g., comprehension) [@McGeown.2015; @Toste.2020], supporting the reading attitudes and habits of Latinx youth... TK add things.

Although shrinking this gap requires a multi-pronged approach (CITE TK), 